package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ID
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_out_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date loginOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.is_enable
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.is_delete
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ID
     *
     * @return the value of admin.ID
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ID
     *
     * @param id the value for admin.ID
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account
     *
     * @return the value of admin.account
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account
     *
     * @param account the value for admin.account
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_time
     *
     * @return the value of admin.login_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_time
     *
     * @param loginTime the value for admin.login_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_out_time
     *
     * @return the value of admin.login_out_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getLoginOutTime() {
        return loginOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_out_time
     *
     * @param loginOutTime the value for admin.login_out_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setLoginOutTime(Date loginOutTime) {
        this.loginOutTime = loginOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.is_enable
     *
     * @return the value of admin.is_enable
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.is_enable
     *
     * @param isEnable the value for admin.is_enable
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.is_delete
     *
     * @return the value of admin.is_delete
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.is_delete
     *
     * @param isDelete the value for admin.is_delete
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}