package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class Referencecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.record_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.gjsd
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date gjsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.rs_dz
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String rsDz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.build
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String build;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.lc
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String lc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.pm
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String pm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.cx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String cx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.rj_mj
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String rjMj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.zx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String zx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.wq
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String wq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.completeDate
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String completedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.jg
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.yt
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String yt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.back1
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String back1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.back2
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.back3
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String back3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.back4
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String back4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referencecase.back5
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date back5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.id
     *
     * @return the value of referencecase.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.id
     *
     * @param id the value for referencecase.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.record_id
     *
     * @return the value of referencecase.record_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.record_id
     *
     * @param recordId the value for referencecase.record_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.gjsd
     *
     * @return the value of referencecase.gjsd
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getGjsd() {
        return gjsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.gjsd
     *
     * @param gjsd the value for referencecase.gjsd
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setGjsd(Date gjsd) {
        this.gjsd = gjsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.rs_dz
     *
     * @return the value of referencecase.rs_dz
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getRsDz() {
        return rsDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.rs_dz
     *
     * @param rsDz the value for referencecase.rs_dz
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setRsDz(String rsDz) {
        this.rsDz = rsDz == null ? null : rsDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.build
     *
     * @return the value of referencecase.build
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getBuild() {
        return build;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.build
     *
     * @param build the value for referencecase.build
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBuild(String build) {
        this.build = build == null ? null : build.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.lc
     *
     * @return the value of referencecase.lc
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getLc() {
        return lc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.lc
     *
     * @param lc the value for referencecase.lc
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setLc(String lc) {
        this.lc = lc == null ? null : lc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.pm
     *
     * @return the value of referencecase.pm
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getPm() {
        return pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.pm
     *
     * @param pm the value for referencecase.pm
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setPm(String pm) {
        this.pm = pm == null ? null : pm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.cx
     *
     * @return the value of referencecase.cx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getCx() {
        return cx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.cx
     *
     * @param cx the value for referencecase.cx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setCx(String cx) {
        this.cx = cx == null ? null : cx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.rj_mj
     *
     * @return the value of referencecase.rj_mj
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getRjMj() {
        return rjMj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.rj_mj
     *
     * @param rjMj the value for referencecase.rj_mj
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setRjMj(String rjMj) {
        this.rjMj = rjMj == null ? null : rjMj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.zx
     *
     * @return the value of referencecase.zx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getZx() {
        return zx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.zx
     *
     * @param zx the value for referencecase.zx
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setZx(String zx) {
        this.zx = zx == null ? null : zx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.wq
     *
     * @return the value of referencecase.wq
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getWq() {
        return wq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.wq
     *
     * @param wq the value for referencecase.wq
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setWq(String wq) {
        this.wq = wq == null ? null : wq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.completeDate
     *
     * @return the value of referencecase.completeDate
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getCompletedate() {
        return completedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.completeDate
     *
     * @param completedate the value for referencecase.completeDate
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setCompletedate(String completedate) {
        this.completedate = completedate == null ? null : completedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.jg
     *
     * @return the value of referencecase.jg
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.jg
     *
     * @param jg the value for referencecase.jg
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setJg(String jg) {
        this.jg = jg == null ? null : jg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.yt
     *
     * @return the value of referencecase.yt
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getYt() {
        return yt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.yt
     *
     * @param yt the value for referencecase.yt
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setYt(String yt) {
        this.yt = yt == null ? null : yt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.back1
     *
     * @return the value of referencecase.back1
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.back1
     *
     * @param back1 the value for referencecase.back1
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.back2
     *
     * @return the value of referencecase.back2
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.back2
     *
     * @param back2 the value for referencecase.back2
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.back3
     *
     * @return the value of referencecase.back3
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.back3
     *
     * @param back3 the value for referencecase.back3
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.back4
     *
     * @return the value of referencecase.back4
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getBack4() {
        return back4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.back4
     *
     * @param back4 the value for referencecase.back4
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBack4(String back4) {
        this.back4 = back4 == null ? null : back4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referencecase.back5
     *
     * @return the value of referencecase.back5
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getBack5() {
        return back5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referencecase.back5
     *
     * @param back5 the value for referencecase.back5
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setBack5(Date back5) {
        this.back5 = back5;
    }
}