package com.spring.mpvue.springbootmpvue.mybatis.po;

public class SysApiConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_api_config.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_api_config.confit_type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer confitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_api_config.sys_user_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_api_config.total_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_api_config.used_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer usedCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_api_config.id
     *
     * @return the value of sys_api_config.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_api_config.id
     *
     * @param id the value for sys_api_config.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_api_config.confit_type
     *
     * @return the value of sys_api_config.confit_type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getConfitType() {
        return confitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_api_config.confit_type
     *
     * @param confitType the value for sys_api_config.confit_type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setConfitType(Integer confitType) {
        this.confitType = confitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_api_config.sys_user_id
     *
     * @return the value of sys_api_config.sys_user_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_api_config.sys_user_id
     *
     * @param sysUserId the value for sys_api_config.sys_user_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_api_config.total_count
     *
     * @return the value of sys_api_config.total_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_api_config.total_count
     *
     * @param totalCount the value for sys_api_config.total_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_api_config.used_count
     *
     * @return the value of sys_api_config.used_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getUsedCount() {
        return usedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_api_config.used_count
     *
     * @param usedCount the value for sys_api_config.used_count
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setUsedCount(Integer usedCount) {
        this.usedCount = usedCount;
    }
}