package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.title
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.service_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_by
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.update_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remote_addr
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String remoteAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_agent
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.request_uri
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String requestUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.method
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.del_flag
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.type
     *
     * @return the value of sys_log.type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.type
     *
     * @param type the value for sys_log.type
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.title
     *
     * @return the value of sys_log.title
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.title
     *
     * @param title the value for sys_log.title
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.service_id
     *
     * @return the value of sys_log.service_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.service_id
     *
     * @param serviceId the value for sys_log.service_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_by
     *
     * @return the value of sys_log.create_by
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_by
     *
     * @param createBy the value for sys_log.create_by
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.update_time
     *
     * @return the value of sys_log.update_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.update_time
     *
     * @param updateTime the value for sys_log.update_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remote_addr
     *
     * @return the value of sys_log.remote_addr
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remote_addr
     *
     * @param remoteAddr the value for sys_log.remote_addr
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr == null ? null : remoteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_agent
     *
     * @return the value of sys_log.user_agent
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_agent
     *
     * @param userAgent the value for sys_log.user_agent
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.request_uri
     *
     * @return the value of sys_log.request_uri
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.request_uri
     *
     * @param requestUri the value for sys_log.request_uri
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri == null ? null : requestUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.method
     *
     * @return the value of sys_log.method
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.method
     *
     * @param method the value for sys_log.method
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.del_flag
     *
     * @return the value of sys_log.del_flag
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.del_flag
     *
     * @param delFlag the value for sys_log.del_flag
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}