package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.open_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.name
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.latitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.longitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.open_id
     *
     * @return the value of user_address.open_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.open_id
     *
     * @param openId the value for user_address.open_id
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.name
     *
     * @return the value of user_address.name
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.name
     *
     * @param name the value for user_address.name
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.latitude
     *
     * @return the value of user_address.latitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.latitude
     *
     * @param latitude the value for user_address.latitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.longitude
     *
     * @return the value of user_address.longitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.longitude
     *
     * @param longitude the value for user_address.longitude
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.create_time
     *
     * @return the value of user_address.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.create_time
     *
     * @param createTime the value for user_address.create_time
     *
     * @mbggenerated Tue Jun 02 15:01:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}